### ISSUE TITLE
move dependencies into relevant plugin

### ISSUE THREAD

**Issue by wzr1337** [wzr1337/viwiServer#44]
plugins have dependencies which are resolved via the general `package.json`right now. 

The plugins shall carry their own package.json to represent their dependencies. 

Problem: The plugins reside in src/ but npm willl only intsall into `node_modules`

a workaround has to be found

**Comment by BenjaminDobler** [comment]
Maybe an approach like the ember cli uses for it`s addons would work. You develop your plugins as npm packages with it`s own package.json. Each Plugin carries it`s own dependencies. Then you just add the plugin to your rsiServer deps. The rsiServer checks it`s dependencies and looks in each package.json keywords. If it finds the keyword "rsiServer-plugin" it knows that it`s a plugin and adds the package to the pluginPaths...

From the embed cli docs:

> Ember CLI will detect the presence of an addon by inspecting each of your applications dependencies and search their package.json files for the presence of ember-addon in the keywords section (see below).

There is a similar discussion about extending the angular cli here: [https://github.com/angular/angular-cli/issues/2906](https://github.com/angular/angular-cli/issues/2906)

**Comment by wzr1337** [comment]
Very good idea,

I will give it a try this week.

How will you add the plugin to the plugin path? Symlink? Move it?

Will the plugins carry only source or also a distance folder?

I would prefer to have just the source for the beginning.. I believe adding
distance as well would complicate the plugin build process, as they need to
build on their own..

What do you think?

**Comment by BenjaminDobler** [comment]
I guess it depends a bit if you do a cli like approach or not. If you only add the sources then you would need the cli i think because it needs to be build before it can be used. Otherwise if you have the dist folder it could just be dynamically loaded. The paths could be added a bit like in node where it does not only look in one defined path for deps (plugins) but in an array ( require('module').globalPaths.push('path to deps'))...
So each plugin path could be added to this array and the rsi server just looks in each of those paths.

This way one could maybe even link plugins which are in different locations which could be handy for development?

**Comment by wzr1337** [comment]
Good idea..

This would need a change in the plugin loader though... As it would be
compatible with the current solution, I would really welcome a preparations
PR that will enable alternative plugin locations

:)

**Comment by BenjaminDobler** [comment]
Ok one last idea :-)
How about having plugins as independent npm modules with it`s own dependencies.
How could such a module project look like? Exactly like the rsiServer today with a plugin folder and your plugin in it! The only difference to the rsiServer would be that it has a postinstall script which copies the content of the plugin folder into the plugin folder of the rsiServer.

So you do npm install myFancyPlugin
1. it will install all dependencies of the plugin like described in the package.json
2. postinstall script copies the plugin folder content into the plugin folder of the rsi server

Advantage? 
1. Each plugin can be tested individually because it has it`s own rsiServer in it!
2. The current lightweight mechanism of adding plugins directly into the rsiServer plugin dir remains and can be optionally used as well.
3. No fancy loading mechanism needed - actually no change to the rsiServer needed at all!

What do you think?

**Comment by wzr1337** [comment]
I would prefer linking or adding nide_modules to the plugin folder search
path.. the copy seems to be quite 'heavy'.

I would also like to be able using npm link etc. for plugins.. this would
work with the node_modules approach..

**Comment by wzr1337** [comment]
I would add an info to the package.json of the rsp* packages, to let the plugin loader just walk through all rsp.* folders in node_modules and check if it is an actuals rsi Server Plugin by evaluation the proprietary attribute in the package.json..
