### ISSUE TITLE
How to test rsiServer with client and plugins?

### ISSUE THREAD

**Issue by wonsuk73** [wzr1337/viwiServer#47]
I have installed rsi server. but I couldn't find the way how to test it with client as well as test for plug-in service. Is there any guide for potential contributors from outside?

**Comment by wzr1337** [comment]
Hi Wonsuk,

you will need to install the plugins as git sub modules. Did you do that? Did it work? 

You can clone with the --recursive flag set, that should clone the sub modules for you too.

Regarding client: there are just the tests in the repo for now. We are actually missing a reference client so far.. android, iOS , web.. would be happy seeing support here :)

**Comment by anawhj** [comment]
In `.gitmodules` file, I could find the description of git submodules, but it seems not to work. So I tried to clone a couple of sub modules manually in `src/plugins`, and install/build/run the server. After that, I can see green logs that describe the plugins(`media` and `medialibrary`) have been successfully registered in the RSI server so that I can send requests(HTTP/WebSocket) and get responses as a JSON format. Some reference that can be used as request queries could be found in the [viwi.service.media](https://www.w3.org/Submission/2016/SUBM-viwi-service-media-20161213/) document.

In addition, I noticed a misspelling at the `git clone` command in README.md as follows:
- git clone https://github.com/wz1337/rsiServer.git --recursive (as is)
- git clone https://github.com/wzr1337/rsiServer.git --recursive (to be)

I briefly looked into the documents from VW's submissions. I think we need to define the scope that needs standardization as a first step, while we proceed to understand the RSI architecture and discuss with some issues.

**Comment by wonsuk73** [comment]
@wzr1337, I did install sub modules after I read @anawhj 's post of this thread. Thanks @anawhj !!
After that I made a simple client using code in README.md. I got the result as below in server side. I seems it work correctly. right?

```
2017-07-28T09:31:58.136Z - debug: [rsiWebSocket] rsiWebSocket.acknowledgeSubscription(): /media/renderers/d6ebfd90-d2c1-11e6-9376-df943f51f0d8
2017-07-28T09:31:58.137Z - debug: [rsiWebSocket] rsiWebSocket._send(): 
{ type: 'subscribe',
  status: 'ok',
  event: '/media/renderers/d6ebfd90-d2c1-11e6-9376-df943f51f0d8' }
2017-07-28T09:31:58.141Z - debug: [rsiWebSocket] rsiWebSocket.sendData(): /media/renderers/d6ebfd90-d2c1-11e6-9376-df943f51f0d8
2017-07-28T09:31:58.141Z - debug: [rsiWebSocket] rsiWebSocket._send(): 
{ type: 'data',
  status: 'ok',
  event: '/media/renderers/d6ebfd90-d2c1-11e6-9376-df943f51f0d8',
  data: 
   { uri: '/media/renderers/d6ebfd90-d2c1-11e6-9376-df943f51f0d8',
     id: 'd6ebfd90-d2c1-11e6-9376-df943f51f0d8',
     name: 'Netflux',
     state: 'idle',
     shuffle: 'off',
     repeat: 'off',
     offset: 0,
     media: 'initialCollection' } }
```

**Comment by wzr1337** [comment]
That looks perfectly fine! Cool

I will work on the 'non working sub module' issue asap

Finally I want to get away from submodules.. because they do not perfectly fit our needs do - as you can see - do not work smoothly

**Comment by wonsuk73** [comment]
@wzr1337 Got it! 👍

**Comment by wzr1337** [comment]
@anawhj I just fixed the typo, Thanks for the hint..

Closing because of : resolved ;)
